### ISSUE TITLE
Is there a way how to continue use Osmosis for getting changes?

### ISSUE THREAD

**Issue by pedro042** [geofabrik/sendfile_osm_oauth_protector#2]
Hi,

I!d like to ask a question in public - this is not issue related to this tool directly. I use osmosis for getting OSM changes, something like

osmosis -q --read-replication-interval workingDirectory=~/replication/  --write-xml-change file=~/replication/changes.osc.gz && \ # continue work

There is probably no way how to tell Osmosis the cookie. Using Osmosis has some advantages - it's fully automated, in case of outage it will read more then one osc.gz file etc.

Time to time I check OSM data for Czech Republic for example for duplicate buildings, orphaned entities (like nodes, way, relations with no tags - I found more than 200.000 orphaned nodes and deleted them). Of course, before deletion 200.000 nodes I asked users who created them if I can delete it. I'm not able to manually check thousands of entities on OSM server, but I'd hate to stop this cleaning proccess.

Is possible, for example, to give me access to the full osc.gz files for example from my IP address?

My OSM nickname is pedro' and/or CzechAddress (it's a bot running continuous import of Czech Republic address places from cadastre to OSM - https://wiki.openstreetmap.org/wiki/Address_import_from_RUIAN).  Good to know who edited addresses.

Any help welcome ;-)

Petr

**Comment by Nakaner** [comment]
https://github.com/openstreetmap/osmosis/pull/40 should fix it.

If the cookie is outdated (currently 48 hours), the server will return some `text/html` instead of GZIP compressed XML. Osmosis will crash. Until I add the missing bits to the pull request, you can use following workaroung: Either do a HTTP HEAD request for any file (e.g. the `state.txt` file) and check if you get status code 200 (301 if cookie is expired). Or you run Osmosis and check its return code. It will raise an exception if it cannot parse the diff. Then it is your time to use (oauth_cookie_client.py](https://github.com/geofabrik/sendfile_osm_oauth_protector/blob/master/oauth_cookie_client.py) to retrieve a new cookie and overwrite `cookie.txt` in your Osmosis replication working directory.

**Comment by Nakaner** [comment]
Osmosis is unmaintained, so there won't be any help in forseeable future. That's why I am closing this ticket now.
